name: Prepare Release

on:
  issue_comment:
    types: [created]

jobs:
  prepare_release:
    # Run only if
    # 1. The comment was made on an Issue 
    # 2. The comment was exactly "/prepare deploy" sans the quotes.
    # 3. The Issue is open.
    # 4. The Issue name is
      # && github.event.comment.user.login == 'samkit-jain'
    if: |
      !github.event.issue.pull_request &&
      github.event.comment.body == '/prepare' &&
      !github.event.issue.closed_at &&
      github.event.issue.state == 'open' &&
      github.event.issue.title == 'prepare release'
    runs-on: ubuntu-latest
    name: Prepare Release

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Sync branch
        id: sync-branch
        shell: bash
        env:
          MERGEABLE_STATUS: ${{ fromJson(steps.get-pr-details.outputs.data).mergeable_state }}
          BASE_BRANCH: production
          HEAD_BRANCH: staging
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions"
          git checkout $HEAD_BRANCH
          git pull origin $HEAD_BRANCH
          git checkout $BASE_BRANCH
          git pull origin $BASE_BRANCH
          git rebase $HEAD_BRANCH
          git push origin $BASE_BRANCH
          echo "::set-output name=message::'PR merged in succesfully.'"

      # Post a success/failure comment to the issue.
      - name: Add comment to isssue
        if: ${{ success() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/issues/{issue_number}/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: Prepare release success. taging synced to production
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Post a failure message when any of the previous steps fail.
      - name: Add failure comment to issue
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/issues/{issue_number}/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: Prepare release failed. Check the Actions execution tab for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
