name: Release

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  release:
    # Run only if
    # 1. The comment was made on an Issue 
    # 2. The comment was exactly "/release" sans the quotes.
    # 3. The Issue is open.
    # 4. The Issue name is
      # && github.event.comment.user.login == 'samkit-jain'
    if: |
      (!github.event.issue.pull_request &&
      github.event.comment.body == '/release' &&
      !github.event.issue.closed_at &&
      github.event.issue.state == 'open' &&
      github.event.issue.title == 'release') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: production

       - name: Debug
        run: |
          echo "GITHUB_EVENT_NAME                         =" "${GITHUB_EVENT_NAME}"
          echo "GITHUB_REF                                =" "${GITHUB_REF}"
          echo "GITHUB_SHA                                =" "${GITHUB_SHA}"
          echo "GITHUB_RUN_ID                             =" "${GITHUB_RUN_ID}"
          echo "GITHUB_REPOSITORY                         =" "${GITHUB_REPOSITORY}"
          echo "GITHUB_WORKSPACE                          =" "${GITHUB_WORKSPACE}"


      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic   # Need an `id` for output variables
        with:
          branches: |
            ['production']
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_REF: refs/heads/production

      # Post a success/failure comment to the issue.
      - name: Add comment to isssue
        if: steps.semantic.outputs.new_release_published == 'true' && github.event_name == 'issue_comment'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/issues/{issue_number}/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: Release success.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Post a failure message when any of the previous steps fail.
      - name: Add failure comment to issue
        if: steps.semantic.outputs.new_release_published == 'false' && github.event_name == 'issue_comment'
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/issues/{issue_number}/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: Release failed. Check the Actions execution tab for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
