name: Deploy Release

on:
  issue_comment:
    types: [created]

jobs:
  deploy_release:
    # Run only if
    # 1. The comment was made on an Issue 
    # 2. The comment was exactly "/prepare deploy" sans the quotes.
    # 3. The Issue is open.
    # 4. The Issue name is
      # && github.event.comment.user.login == 'samkit-jain'
    if: |
      !github.event.issue.pull_request &&
      github.event.comment.body == '/deploy' &&
      !github.event.issue.closed_at &&
      github.event.issue.state == 'open' &&
      github.event.issue.title == 'release'
    runs-on: ubuntu-latest
    name: Deploy Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Post a success/failure comment to the issue.
      - name: Add comment to isssue
        if: ${{ success() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/issues/{issue_number}/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: Deploy success.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Post a failure message when any of the previous steps fail.
      - name: Add failure comment to issue
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repository}/issues/{issue_number}/comments
          repository: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          body: Deploy failed. Check the Actions execution tab for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
